### ISSUE TITLE
Link area in superscripts too small in DVI -> PS -> PDF route

### ISSUE THREAD

**Issue by moewew** [latex3/hyperref#115] opened 2020-01-16 17:15 UTC
Consider the following MWE also shared [in the TeX.SX chat](https://chat.stackexchange.com/transcript/message/53242241#53242241)
```latex
\documentclass{article}

\usepackage[super]{natbib}
\usepackage{hyperref}

\begin{document}
Text \cite{sigfridsson}
\begin{thebibliography}{1}
\bibitem{sigfridsson} Sigfridsson
\end{thebibliography}
\end{document}
```
or the smaller `hyperref`-only MWE recommended by Ulrike [in the chat](https://chat.stackexchange.com/transcript/message/53242873#53242873)
```latex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\makeatletter
Text\textsuperscript{\hyper@linkstart{cite}{cite.XXX}1\hyper@linkend}
\end{document}
```

When compiled with LaTeX -> dvips -> ps2pdf the output is
![Namenlos-6c](https://user-images.githubusercontent.com/6755835/72546710-959e2380-388b-11ea-904f-3b11a0139e42.png)
with a surprisingly small link area.

When compiled with pdfLaTeX the PDF looks as I would expect
![Namenlos-6d](https://user-images.githubusercontent.com/6755835/72546871-d39b4780-388b-11ea-9cc0-ddc02862076b.png)

*edit*: Forgot the link to the TeX.SX question that sparked my interest in this in the first place: https://tex.stackexchange.com/q/524407/35864

**Comment by u-fischer** [comment] 2020-01-16 17:49
The problem is that  `\textsuperscript` sets `\baselineskip` to 0pt:

```
\def\@textsuperscript#1{%
  {\m@th\ensuremath{^{\mbox{\fontsize\sf@size\z@#1}}}}}
```

On the other side `\hyper@linkend` uses `\baselineskip`:

```
\def\hyper@linkend{%
  \literalps@out{\strip@pt@and@otherjunk\baselineskip\space H.L}%
```
Setting `\baselineskip` to a positive value resolves the problem:

```
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\makeatletter
Text\textsuperscript{\hyper@linkstart{cite}{cite.XXX}1\hyper@linkend}

Text\textsuperscript{\hyper@linkstart{cite}{cite.XXX}1\baselineskip=8pt\hyper@linkend}
\end{document}

```

![image](https://user-images.githubusercontent.com/4047173/72549294-b87f0680-3890-11ea-8d65-71248198ac7c.png)


The main question is where to do this (I don't know why `\textsuperscript` sets it to zero.)

**Comment by u-fischer** [comment] 2021-02-09 10:09
This has been resolved in the  latex kernel.

**Closed by u-fischer** 2021-02-09 10:09 UTC
