### ISSUE TITLE
linktoc=none produces links in the TOC anyway

### ISSUE THREAD

**Issue by jefftrull** [latex3/hyperref#192] opened 2021-06-04 07:24 UTC
I've been trying without success to have unstyled section names in the TOC for my Beamer presentation, but even with `linktoc=none` the section names are links:

```latex
\documentclass[11pt,aspectratio=169]{beamer}
\hypersetup{linktoc=none, colorlinks=false}

\begin{document}

\maketitle
\begin{frame}{Outline}
\tableofcontents
\end{frame}

\section{First Section}
\begin{frame}{Frame1}
frame 1 contents
\end{frame}

\begin{frame}{Frame 2}
  frame 2 contents
\end{frame}

\section{Second Section}
\begin{frame}{Frame2.1}
  frame 2.1 contents
\end{frame}

\end{document}

```
The second slide has a TOC consisting of three clickable links, despite the `linktoc=none`.

**Comment by muzimuzhi** [comment] 2021-06-04 09:01
In `beamer`, hyperlinks of section-like items in toc are directly created by `\hyperlink`, hence are not affected by `hyperref`'s package option `linktoc`. `NoHyper` environment which stops the hypertext functions doing anything (see `texdoc hyperref`, sec. 4) will do the work here.

```tex
\documentclass[11pt,aspectratio=169]{beamer}

\begin{document}

\maketitle
\begin{frame}{Outline}
\begin{NoHyper}
  \tableofcontents
\end{NoHyper}
\end{frame}

\section{First Section}
\begin{frame}{Frame1}
frame 1 contents
\end{frame}

\begin{frame}{Frame 2}
  frame 2 contents
\end{frame}

\section{Second Section}
\begin{frame}{Frame2.1}
  frame 2.1 contents
\end{frame}

\end{document}
```

**Comment by jefftrull** [comment] 2021-06-05 00:27
Thank you. Would it be reasonable for me to propose this as a Beamer bug? In the sense that unlike `article`, the TOC does not obey that setting?

**Comment by muzimuzhi** [comment] 2021-06-05 08:36
`beamer` implements its own toc scheme, hence the normal `hyperref` patch to toc staffs doesn't work. I would take this as a compatibility issue.

**Comment by u-fischer** [comment] 2021-06-05 08:44
> Would it be reasonable for me to propose this as a Beamer bug?

It is not a bug. A class like beamer doesn't have to react to package options. If you want such a feature the right place to ask for it is the beamer issue tracker, but imho using NoHyper is a sensible solution. I'm closing here as it is not a hyperref bug.

**Closed by u-fischer** 2021-06-05 08:44 UTC

**Comment by jefftrull** [comment] 2021-06-05 17:48
As you can see from the issue I opened in Beamer, _consistency_ may be the biggest issue here. Most `hyperref` options work just fine in Beamer, - but not this one.
