### ISSUE TITLE
Spurious ".pdf" added to the first argument of \href if inside \ExplSyntaxOn/Off

### ISSUE THREAD

**Issue by dbitouze** [latex3/hyperref#188] opened 2021-04-25 10:25 UTC
For the record, I open this issue for what has been discussed [here](https://tex.stackexchange.com/q/304980/18401).

As shown byt the following MCE, a spurious ".pdf" is added to the URL given in the first argument of `\href` if (and only if, AFAICS) the latter is used inside `\ExplSyntaxOn`/`\ExplSyntaxOff`.

```latex
\begin{filecontents}[overwrite]{mynicepackage.sty}
\RequirePackage{hyperref}
\ProvidesExplPackage{mynicepackage}{2021/04/25} {0.1}{mynicepackage}
\ExplSyntaxOn
\cs_new_protected:Nn \__npkg_package:nnn
{
  \texorpdfstring{%
    \IfBooleanTF {#1}
    {%
      \textsf{#3}
    }{
      \tl_if_empty:nTF {#2}
      {%
        \href{https://www.ctan.org/pkg/#3}{\textsf{#3}}%
      }{%
        \href{#2}{\textsf{#3}}%
      }%
    }
  }{
    \textsf{#3}%
  }
}%
\NewDocumentCommand{\package}{ s O{} m } {
  \__npkg_package:nnn {#1}{#2}{#3}
}
\ExplSyntaxOff
\end{filecontents}

\documentclass{article}
\usepackage{mynicepackage}
\begin{document}
\package{foo} target's:
\begin{itemize}
\item is         \url{https://www.ctan.org/pkg/foo.pdf}
\item should be  \url{https://www.ctan.org/pkg/foo}
\end{itemize}
\end{document}
```

**Comment by u-fischer** [comment] 2021-04-25 10:47
Yes, \href tries to be clever. If you want the exact rules:

~~~~
href creates different link types.

If there is a colon (catcode12) :
  -> if prefix = file: GoToR
  -> if prefix = run:  Launch
  -> if prefix empty:  GoToR
  -> rest: URI

If there is no colon:
  if there is a dot:
    -> extension: pdf  GoToR
    -> else URI
  if there is no dot: GoToR
~~~~

So in expl3 code you have to use `\char_generate:nn{58}{12}`.  Personally I would suggest to define a constant for the prefix:

~~~~
\begin{filecontents}[overwrite]{mynicepackage.sty}
\RequirePackage{hyperref}
\ProvidesExplPackage{mynicepackage}{2021/04/25} {0.1}{mynicepackage}
\tl_const:Nx\c__npkg_httpsprefix_tl{https\char_generate:nn{58}{12}//}
\cs_new_protected:Nn \__npkg_package:nnn
{
  \texorpdfstring{%
    \IfBooleanTF {#1}
    {%
      \textsf{#3}
    }{
      \tl_if_empty:nTF {#2}
      {%
        \href{\c__npkg_httpsprefix_tl www.ctan.org/pkg/#3}{\textsf{#3}}%
        \quad or \quad
        \href{https\char_generate:nn{58}{12}//www.ctan.org/pkg/#3}{\textsf{#3}}%
      }{%
        \href{#2}{\textsf{#3}}%
      }%
    }
  }{
    \textsf{#3}%
  }
}%
\NewDocumentCommand{\package}{ s O{} m } {
  \__npkg_package:nnn {#1}{#2}{#3}
}
\end{filecontents}

\documentclass{article}
\usepackage{mynicepackage}
\begin{document}
\package{foo} target's:
\begin{itemize}
\item is \url{https://www.ctan.org/pkg/foo}
\end{itemize}
~~~~


With the new pdfmanagement you can also use `\hrefurl` instead of `\href`. That doesn't try to guess.

**Comment by u-fischer** [comment] 2021-06-05 08:52
This is not a bug but the intended behaviour, so closing now.

**Closed by u-fischer** 2021-06-05 08:52 UTC

**Comment by dbitouze** [comment] 2021-06-05 09:43
> This is not a bug but the intended behaviour, so closing now.

Nothing more handy than this weird `\tl_const:Nx\c__npkg_httpsprefix_tl{https\char_generate:nn{58}{12}//}` is planned?
