### ISSUE TITLE
Link across two pages is visually broken (includes header/footer)

### ISSUE THREAD

**Issue by genodeftest** [latex3/hyperref#54] opened 2018-02-09 20:00 UTC
See https://tex.stackexchange.com/q/330669 for a MWE, a result (picture) and a workaround.

When a link spans across pages, page header and footer also become part of this link, which looks broken.

**Comment by davidcarlisle** [comment] 2018-02-09 20:26
Thanks for posting that here. I can't promise an immediate fix, but at
least with an open issue, it won't get lost.

**Comment by u-fischer** [comment] 2018-12-14 18:42
There is imho nothing hyperref can do here. The problem is that fancyhdr adds a box around the footer (and the header). This means that now the footer has the same (or greater) box nesting level as the main text body and the lowlevel primitive \pdfstartlink will include the footer in the link. With xetex you could interrupt the link in the footer, but nothing similar  exists for pdftex or luatex.

**Comment by u-fischer** [comment] 2022-11-13 15:53
This problem is resolved in a current texlive if the pdf management is loaded. https://tex.stackexchange.com/a/578405/2388

**Closed by u-fischer** 2022-11-13 15:53 UTC
